### ISSUE TITLE
Autotraits

### ISSUE THREAD

**Issue by dtolnay** [skade/ffi-opaque#1]
This library doesn't quite produce opaque types because it assumes the underlying type is Send, Sync, Unpin.

Since there is no stable way to do negative handwritten autotrait impls, only positive ones, I believe it would be more correct for `opaque!` to produce a type that is !Send, !Sync, !Unpin in order to be truly opaque.

**Comment by skade** [comment]
Hi @dtolnay, this is a good point! I'll also make a mental note to also add this to the section in the Nomicon where I got this from ;).

https://doc.rust-lang.org/nomicon/ffi.html#representing-opaque-structs

**Comment by skade** [comment]
I'm currently considering to use

```rust
#[repr(C)]
struct opaque_t {
    _priv: [*mut u8; 0]
}
```

That type should not be Send, Sync or Unpin. Is there anything problematic I may be missing?

**Comment by nvzqz** [comment]
@skade in 533bfa6b63dc625b8c6b2e1320fb7651c9f548b0 the assertion you want is [`assert_not_impl_any`](https://docs.rs/static_assertions/1.1.0/static_assertions/macro.assert_not_impl_any.html) since you want to ensure it's not any of those traits. `assert_not_impl_all` will pass if any trait but one is implemented.

**Comment by skade** [comment]
@nvzqz good catch, and obviously, *mut u8 is `Unpin`. :/

**Comment by nvzqz** [comment]
I think https://github.com/skade/ffi-opaque/pull/3 addresses the remaining concerns in this issue.

**Comment by dtolnay** [comment]
Looks good. Yeah `[*mut u8; 0]` was not appropriately aligned. I filed #4 to follow up with tests.

**Comment by skade** [comment]
Merged #5 to fix #4. I'll see what I'm going to do with the nomicon :).

Thanks for the help!
