### ISSUE TITLE
Test FFI safety

### ISSUE THREAD

**Issue by dtolnay** [skade/ffi-opaque#2]
Given the name of the crate I would expect to have something to verify that the generated data structure is considered FFI-safe by rustc. I've seen rustc periodically introduce regressions in what is considered to be FFI-safe.

Something like:

```rust
#[deny(improper_ctypes, warnings)]
extern "C" {
    pub fn f(_: *const leveldb_t);
}
```

**Comment by nvzqz** [comment]
I tried making a macro for this (https://github.com/nvzqz/static-assertions-rs/pull/31), but `#[deny]` and `#[forbid]` do not pass through macros (https://github.com/rust-lang/rust/issues/67720).

**Comment by skade** [comment]
Implemented in: Thanks for the suggestion!

https://github.com/skade/ffi-opaque/commit/533bfa6b63dc625b8c6b2e1320fb7651c9f548b0#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759
